(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-auto-commit 'ignore)
 '(company-auto-complete 'ignore)
 '(company-box-backends-colors nil t)
 '(company-box-max-candidates 20 t)
 '(company-box-show-single-candidate t t)
 '(company-dabbrev-code-ignore-case t)
 '(company-dabbrev-downcase nil)
 '(company-echo-delay 0 t)
 '(company-emoji-insert-unicode nil t)
 '(company-flx-mode t t)
 '(company-global-modes t)
 '(company-idle-delay 0.5)
 '(company-lsp-async t)
 '(company-lsp-cache-candidates t t)
 '(company-lsp-enable-recompletion nil)
 '(company-lsp-enable-snippet t)
 '(company-minimum-prefix-length 2)
 '(company-quickhelp-delay 0.8)
 '(company-show-numbers t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-flip-when-above t)
 '(company-tooltip-idle-delay 0.1)
 '(company-tooltip-limit 10)
 '(company-tooltip-minimum 10)
 '(custom-safe-themes
   '("d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "c74fff70a4cc37e2348dd083ae572c8b4baab4f6fb86adae5e0f2139a63e9a96" "2beaaef4f47f22c89948fdb3859799f8f2b64c1282ec21d71d6df49d68e68862" default))
 '(dimmer-buffer-exclusion-regexps
   '(".*Minibuf.*" ".*which-key.*" ".*NeoTree.*" ".*Messages.*" ".*Async.*" ".*Warnings.*" ".*LV.*" ".*Ilist.*"))
 '(dimmer-exclusion-regexp-list
   '(".*Minibuf.*" ".*which-key.*" ".*NeoTree.*" ".*Messages.*" ".*Async.*" ".*Warnings.*" ".*LV.*" ".*Ilist.*"))
 '(dimmer-fraction 0.5)
 '(doom-modeline-buffer-file-name-style 'truncate-with-project)
 '(doom-modeline-icon t)
 '(doom-modeline-major-mode-icon nil)
 '(doom-modeline-minor-modes nil)
 '(doom-themes-enable-bold t)
 '(doom-themes-enable-italic t)
 '(elm-format-on-save nil)
 '(exec-path-from-shell-check-startup-files nil t)
 '(exec-path-from-shell-variables '("PATH" "GOPATH"))
 '(frame-background-mode 'dark)
 '(git-gutter:added-sign "+")
 '(git-gutter:deleted-sign "-")
 '(git-gutter:modified-sign "~")
 '(js-indent-level 2 t)
 '(lsp-auto-guess-root t)
 '(lsp-document-sync-method nil)
 '(lsp-elm-elm-analyse-trigger "change")
 '(lsp-elm-elm-format-path "elm-format")
 '(lsp-elm-elm-path "elm")
 '(lsp-elm-elm-test-path "elm-test")
 '(lsp-elm-server-install-dir "~/.elm-language-server")
 '(lsp-enable-snippet t)
 '(lsp-log-io nil)
 '(lsp-prefer-flymake nil t)
 '(lsp-print-io t)
 '(lsp-print-performance nil)
 '(lsp-response-timeout 10)
 '(lsp-trace t t)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-doc-header t)
 '(lsp-ui-doc-include-signature nil)
 '(lsp-ui-doc-max-height 30)
 '(lsp-ui-doc-max-width 120)
 '(lsp-ui-doc-position 'at-point)
 '(lsp-ui-doc-use-childframe t)
 '(lsp-ui-doc-use-webkit t)
 '(lsp-ui-flycheck-enable t t)
 '(lsp-ui-imenu-enable nil)
 '(lsp-ui-imenu-kind-position 'top)
 '(lsp-ui-peek-enable t)
 '(lsp-ui-peek-fontify 'on-demand)
 '(lsp-ui-peek-list-width 50)
 '(lsp-ui-peek-peek-height 20)
 '(lsp-ui-sideline-enable nil)
 '(lsp-ui-sideline-ignore-duplicate t)
 '(lsp-ui-sideline-show-code-actions t)
 '(lsp-ui-sideline-show-diagnostics nil)
 '(lsp-ui-sideline-show-hover t)
 '(lsp-ui-sideline-show-symbol t)
 '(magit-auto-revert-mode nil)
 '(package-selected-packages
   '(lsp-ui lsp-mode tide diff-hl yasnippet magit diffview json-mode doom-modeline posframe beacon use-package python-mode company-box sublime-theme dimmer dtrt-indent scss-mode ## yaml-mode go-mode add-node-modules-path exec-path-from-shell nova-theme elm-mode web-mode helm-projectile projectile auto-complete typescript-mode js2-mode sass-mode company-quickhelp company helm-descbinds helm))
 '(projectile-enable-caching t)
 '(safe-local-variable-values '((elm-format-elm-version . "0.18")))
 '(scss-compile-at-save nil t)
 '(show-paren-delay 0)
 '(show-paren-mode t)
 '(show-paren-style 'mixed)
 '(show-paren-when-point-in-periphery t)
 '(show-paren-when-point-inside-paren t)
 '(vc-annotate-background "#2b303b")
 '(vc-annotate-color-map
   (list
    (cons 20 "#A3BE8C")
    (cons 40 "#bbbe86")
    (cons 60 "#d3be80")
    (cons 80 "#ECBE7B")
    (cons 100 "#e2ab77")
    (cons 120 "#d99973")
    (cons 140 "#D08770")
    (cons 160 "#cc8294")
    (cons 180 "#c97db8")
    (cons 200 "#c678dd")
    (cons 220 "#c370b6")
    (cons 240 "#c16890")
    (cons 260 "#BF616A")
    (cons 280 "#a35f69")
    (cons 300 "#875e68")
    (cons 320 "#6b5c67")
    (cons 340 "#65737E")
    (cons 360 "#65737E")))
 '(vc-annotate-very-old-color nil)
 '(web-mode-code-indent-offset 2)
 '(web-mode-comment-style 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-pairing nil)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 1)
 '(web-mode-style-padding 1))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:background nil))))
 '(company-scrollbar-bg ((t (:background "#333"))))
 '(company-scrollbar-fg ((t (:background "deep sky blue"))))
 '(company-tooltip ((t (:inherit default :foreground "#c0c5ce" :background "#333"))))
 '(company-tooltip-annotation ((t (:foreground "white smoke"))))
 '(company-tooltip-annotation-selection ((t (:foreground "black"))))
 '(company-tooltip-common ((t (:foreground "orange"))))
 '(company-tooltip-common-selection ((t (:foreground "black"))))
 '(company-tooltip-selection ((t (:foreground "black" :background "deep sky blue"))))
 '(flymake-posframe-foreground-face ((t (:foreground "white"))))
 '(git-gutter:added ((t (:foreground "#50fa7b" :background "#50fa7b"))))
 '(git-gutter:deleted ((t (:foreground "#ff79c6" :background "#ff79c6"))))
 '(git-gutter:modified ((t (:foreground "#f1fa8c" :background "#f1fa8c"))))
 '(show-paren-match ((nil (:background "#44475a" :foreground "#f1fa8c")))))
